#!/bin/bash
set -e

source /usr/local/rvm/scripts/rvm

echo "Installing dependencies with Bundler..."
bundle install

echo "Now starting Unicorn workers..."
bundle exec unicorn -D -c config/unicorn.rb
